if (APPLE)
    message("Configured macOS ONNX Runtime path: ${CMAKE_CURRENT_LIST_DIR}/macos")
    set(OnnxRuntime_DIR "${CMAKE_CURRENT_LIST_DIR}/macos")
elseif (WIN32)
    if (CMAKE_CL_64)
        message("Configured Windows ONNX Runtime x64 path: ${CMAKE_CURRENT_LIST_DIR}/windows-x64")
        set(OnnxRuntime_DIR "${CMAKE_CURRENT_LIST_DIR}/windows-x64")
    else ()
        message("Configured Windows ONNX Runtime x86 path: ${CMAKE_CURRENT_LIST_DIR}/windows-x86")
        set(OnnxRuntime_DIR "${CMAKE_CURRENT_LIST_DIR}/windows-x86")
    endif ()
elseif (UNIX)
    message("Configured Linux ONNX Runtime path: ${CMAKE_CURRENT_LIST_DIR}/linux")
    set(OnnxRuntime_DIR "${CMAKE_CURRENT_LIST_DIR}/linux")
endif ()

